# Generated by Django 5.0.6 on 2024-05-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOrService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_or_service', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MaterialsOrServices',
            },
        ),
        # migrations.CreateModel(
        #     name='VendorOrder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=150, unique=True)),
                ('price_per_unit', models.FloatField()),
                ('phone_number', models.FloatField()),
                ('email_address', models.EmailField(max_length=150)),
                ('is_reliable', models.BooleanField(default=False)),
            ],
        ),
    ]
