# Generated by Django 5.0.6 on 2024-05-16 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_delete_vendororder_vendors_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='vendors',
    #         name='created_by',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
    #         preserve_default=False,
    #     ),
    #     migrations.AddField(
    #         model_name='vendors',
    #         name='material_sold',
    #         field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='material_provided', to='admin_dashboard.materialorservice'),
    #         preserve_default=False,
    #     ),
    # ]
