# Generated by Django 5.0.6 on 2024-05-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_vendors_created_by_vendors_material_sold'),
        ('items', '0003_vendororder_delivery_date_vendororder_order_date_and_more'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='VendorOrder',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('quantity', models.PositiveIntegerField()),
    #             ('order_date', models.DateTimeField(auto_now_add=True)),
    #             ('delivery_date', models.DateTimeField(blank=True, null=True)),
    #             ('status', models.CharField(default='Pending', max_length=50)),
    #             ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='items.ordering')),
    #             ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sold', to='admin_dashboard.materialorservice')),
    #             ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.vendors')),
    #         ],
    #     ),
    # ]
