# Generated by Django 5.0.6 on 2024-06-03 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_vendors_material_sold_vendororder'),
        ('items', '0004_payment_amount_payment_created_at_payment_updated_at_and_more'),
    ]