# Generated by Django 5.0.6 on 2024-06-20 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_material_vendororder'),
        ('items', '0007_alter_product_material_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialOrService',
        ),
        migrations.AddField(
            model_name='vendors',
            name='material_sold',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='material_provided', to='admin_dashboard.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendororder',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='items.ordering'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sold', to='admin_dashboard.material'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.vendors'),
        ),
    ]
