# Generated by Django 5.0.6 on 2024-05-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('admin_dashboard', '0004_delete_vendororder'),
        ('items', '0001_initial'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='VendorOrder',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('quantity', models.PositiveIntegerField()),
    #             ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='items.ordering')),
    #             ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sold', to='admin_dashboard.materialorservice')),
    #             ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.vendors')),
    #         ],
    #     ),
    # ]
