# Generated by Django 5.0.6 on 2024-05-16 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_vendororder'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='vendororder',
    #         name='delivery_date',
    #         field=models.DateTimeField(blank=True, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='vendororder',
    #         name='order_date',
    #         field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
    #         preserve_default=False,
    #     ),
    #     migrations.AddField(
    #         model_name='vendororder',
    #         name='status',
    #         field=models.CharField(default='Pending', max_length=50),
    #     ),
    # ]
