# Generated by Django 5.0.6 on 2024-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_product_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_outsourced',
            field=models.BooleanField(default=False),
        ),
    ]
