# Generated by Django 5.0.6 on 2024-06-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_material_vendororder'),
        ('items', '0006_product_is_outsourced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admin_dashboard.material'),
        ),
    ]
