# Generated by Django 5.0.6 on 2024-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_product_material_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_outsourced',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
