# Generated by Django 5.0.6 on 2024-07-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_product_is_outsourced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_outsourced',
        ),
    ]
